#!/usr/bin/env bash

package="$1"

get_vars_from_file() {
  local names_pattern="$1";shift
  local content_pattern='[a-zA-Z0-9.:/_-]*'
  local value_pattern='('"$content_pattern"'|'\'"$content_pattern"\''|"'"$content_pattern"'")'
  grep -E '^'"$names_pattern"'='"$value_pattern"'$' "$@"
}

if [ -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  eval "$(get_vars_from_file 'BINS' "$BASHER_PACKAGES_PATH/$package/package.sh")"
  IFS=: read -ra bins <<< "$BINS"
fi

if [ -z "$bins" ]; then
  if [ -e "$BASHER_PACKAGES_PATH/$package/bin" ]; then
    bins=("$BASHER_PACKAGES_PATH/$package"/bin/*)
    bins=("${bins[@]##*/}")
    bins=("${bins[@]/#/bin/}")
  else
    bins=()
    while IFS= read -r -d '' f; do
      bins[${#bins[@]}]="${f##*/}"
    done < <(find "$BASHER_PACKAGES_PATH/$package" -maxdepth 1 \( -perm -u+x -type f -or -type l \) -print0)
  fi
fi

for bin in "${bins[@]}"
do
  name="${bin##*/}"
  if ${REMOVE_EXTENSION:-false}; then
    name="${name%%.*}"
  fi
  rm -f "$BASHER_INSTALL_BIN/${name}"
done
