#!/usr/bin/env bash
#
# Usage: basher _deps <package>
# Summary: Globally installs package runtime dependencies
#
# Installs the package dependencies, specified with the
# DEPS= variable on package.sh.
#
# Example: DEPS=username/repo1:otheruser/repo2

set -e

get_vars_from_file() {
  local names_pattern="$1";shift
  local content_pattern='[a-zA-Z0-9.:/_-]*'
  local value_pattern='('"$content_pattern"'|'\'"$content_pattern"\''|"'"$content_pattern"'")'
  grep -E '^'"$names_pattern"'='"$value_pattern"'$' "$@"
}

if [ "$#" -ne 1 ]; then
  basher-help _deps
  exit 1
fi

package="$1"

if [ ! -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  exit
fi

shopt -s nullglob

eval "$(get_vars_from_file 'DEPS' "$BASHER_PACKAGES_PATH/$package/package.sh")"
IFS=: read -ra deps <<< "$DEPS"

for dep in "${deps[@]}"
do
  basher-install "$dep"
done
