#!/usr/bin/env bash

package="$1"

get_vars_from_file() {
  local names_pattern="$1";shift
  local content_pattern='[a-zA-Z0-9.:/_-]*'
  local value_pattern='('"$content_pattern"'|'\'"$content_pattern"\''|"'"$content_pattern"'")'
  grep -E '^'"$names_pattern"'='"$value_pattern"'$' "$@"
}

if [ ! -e "$BASHER_PACKAGES_PATH/$package/package.sh" ]; then
  exit
fi

shopt -s nullglob

eval "$(get_vars_from_file '(BASH_COMPLETIONS|ZSH_COMPLETIONS)' "$BASHER_PACKAGES_PATH/$package/package.sh")"
IFS=: read -ra bash_completions <<< "$BASH_COMPLETIONS"
IFS=: read -ra zsh_completions <<< "$ZSH_COMPLETIONS"

for completion in "${bash_completions[@]}"
do
  mkdir -p "$BASHER_PREFIX/completions/bash"
  ln -sf "$BASHER_PACKAGES_PATH/$package/$completion" "$BASHER_PREFIX/completions/bash/${completion##*/}"
done

for completion in "${zsh_completions[@]}"
do
  target="$BASHER_PACKAGES_PATH/$package/$completion"
  if grep -q "#compdef" "$target"; then
    mkdir -p "$BASHER_PREFIX/completions/zsh/compsys"
    ln -sf "$target" "$BASHER_PREFIX/completions/zsh/compsys/${completion##*/}"
  else
    mkdir -p "$BASHER_PREFIX/completions/zsh/compctl"
    ln -sf "$target" "$BASHER_PREFIX/completions/zsh/compctl/${completion##*/}"
  fi
done
